name: CI

on: [pull_request, push]

jobs:
  SwiftFormat:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: Lint
        run: swiftformat --lint .

  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test target
        run: swift test -v --enable-code-coverage
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash) -D ./.build -J Lit

  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: YOCKOW/Action-setup-swift@v1.1.0
      - name: Test target
        run: swift test -v --enable-code-coverage
      - name: Upload coverage report
        run: bash <(curl -s https://codecov.io/bash) -D ./.build -J Lit
